# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testreddit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftGifOrigin', '~> 1.6.1'
  
  target 'testredditTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testredditUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
